### ISSUE TITLE
항상 pull request 전 eslint를 수동으로 실행시켜야 하는 문제

### ISSUE THREAD

**Issue by algoORgoal** [Majorfolio/majorfolio-frontend#10]
# Description

#9 에서 발생한 문제를 해결하기 위해서는 매번 eslint와 prettier를 개발자가 수동으로 실행시켜야 합니다. 개발자이 일일이 해주어야 되다 보니 생산성이 떨어지는 문제가 발생합니다.

# Managing git hooks(local) and setting up a CI(Continunous Integration) Workflow(remote)

항상 코드에 eslint 에러가 없는지 확인하는 과정을 거치는 것이 번거롭습니다. 따라서 local machine에서 eslint error가 있는지, remote repsitory에서도 pull request하려는 branch에 eslint error가 있는지 자동으로 확인해줄 수 있다면 생산성이 올라갈 것으로 생각합니다.

1. **Managing git hooks**(local strategy)
Git hooks란 git에서 특정 이벤트(commit, push)가 발생했을 때 실행되는 script를 의미합니다. Git hooks를 사용하면 local machine에서 commit을 할 때 eslint를 실행시키고 에러가 있다면 cancel시킬 수 있습니다.

2. **Setting up a CI Workflow**(remote strategy)
Pull Request가 생성되거나 업데이트 되었을 때, github repository에서 해당 pull request가 eslint error가 없는지 확인을 해줘야 합니다. 이를 github actions로 설정해줄 수 있습니다. Github action workflow을 설정하는 방법은 다음과 같습니다.

1. respotiory에 .github/workflows라는 이름의 디렉토리를 만든다.
2. yml 확장자의 파일을 만들고 해당 코드를 넣는다.

```
name: ESLint Check

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint
```
